In [1]:
import json
import pandas as pd
import ast

In [ ]:
data = []
with open('data/output_steam_games.json') as f:
    for line in f:
        data.append(json.loads(line))

In [ ]:
df_games = pd.DataFrame(data)

In [ ]:
df_games.head(2)

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561197970982479,76561197970982479,"[{'item_id': '10', 'item_name': 'Counter-Strik...",277.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,js41637,76561198035864385,"[{'item_id': '10', 'item_name': 'Counter-Strik...",888.0

In [ ]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       24083 non-null  object
 1   genres          28852 non-null  object
 2   app_name        32133 non-null  object
 3   title           30085 non-null  object
 4   url             32135 non-null  object
 5   release_date    30068 non-null  object
 6   tags            31972 non-null  object
 7   reviews_url     32133 non-null  object
 8   discount_price  225 non-null    float64
 9   specs           31465 non-null  object
 10  price           30758 non-null  object
 11  early_access    32135 non-null  object
 12  id              32133 non-null  object
 13  metascore       2677 non-null   object
 14  developer       28836 non-null  object
 15  user_id         88310 non-null  object
 16  steam_id        88310 non-null  object
 17  items           88310 non-null  object
 18  items_count     88310 non-null  float64
dtypes: float64(2), object(17)
memory usage: 17.5+ MB

In [ ]:
df_games_copy = df_games.copy()

In [ ]:
#vemos que poseen datos similares Entonces completamos los fatantes en uno con el otro
df_games_copy['app_name'].fillna(df_games_copy['title'], inplace=True)
df_games_copy['title'].fillna(df_games_copy['app_name'], inplace=True)

In [ ]:
#verifico las filas con muchos NaN
df_games_copy[df_games_copy.isnull().sum(axis=1)>=15]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561197970982479,76561197970982479,"[{'item_id': '10', 'item_name': 'Counter-Strik...",277.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,js41637,76561198035864385,"[{'item_id': '10', 'item_name': 'Counter-Strik...",888.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,evcentric,76561198007712555,"[{'item_id': '1200', 'item_name': 'Red Orchest...",137.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Riot-Punch,76561197963445855,"[{'item_id': '10', 'item_name': 'Counter-Strik...",328.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,doctr,76561198002099482,"[{'item_id': '300', 'item_name': 'Day of Defea...",541.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561198326700687,76561198326700687,"[{'item_id': '11020', 'item_name': 'TrackMania...",177.0
88307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XxLaughingJackClown77xX,76561198328759259,[],0.0
88308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561198329548331,76561198329548331,"[{'item_id': '304930', 'item_name': 'Unturned'...",7.0
88309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,edward_tremethick,76561198331598578,[],0.0
88384,NaN,NaN,NaN,NaN,http://store.steampowered.com/,NaN,NaN,NaN,14.99,NaN,19.99,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Filtramos las que contienen NaN distinto al analisis anterior
df_games_copy = df_games_copy[df_games_copy.isnull().sum(axis=1)!=15]
df_games_copy.reset_index(drop=True, inplace=True) 
df_games_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32134 entries, 0 to 32133
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       24083 non-null  object
 1   genres          28852 non-null  object
 2   app_name        32133 non-null  object
 3   title           32133 non-null  object
 4   url             32134 non-null  object
 5   release_date    30068 non-null  object
 6   tags            31972 non-null  object
 7   reviews_url     32133 non-null  object
 8   discount_price  224 non-null    float64
 9   specs           31465 non-null  object
 10  price           30757 non-null  object
 11  early_access    32134 non-null  object
 12  id              32133 non-null  object
 13  metascore       2677 non-null   object
 14  developer       28836 non-null  object
 15  user_id         0 non-null      object
 16  steam_id        0 non-null      object
 17  items           0 non-null      object
 18  items_count     0 non-null      float64
dtypes: float64(2), object(17)
memory usage: 4.7+ MB

In [ ]:
df_games_copy.isnull().sum()

publisher          8051
genres             3282
app_name              1
title                 1
url                   0
release_date       2066
tags                162
reviews_url           1
discount_price    31910
specs               669
price              1377
early_access          0
id                    1
metascore         29457
developer          3298
user_id           32134
steam_id          32134
items             32134
items_count       32134
dtype: int64

In [ ]:
#vemos si podemos salvar algunos de las filas con id NaN
df_games_copy[df_games_copy.id.isnull()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
30960,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,91,"Rocksteady Studios,Feral Interactive (Mac)",NaN,NaN,NaN,NaN

In [ ]:
#completamos el id con steamId
df_games_copy.id.iloc[30960] = 200260
df_games_copy.reset_index(drop=True, inplace=True)

In [ ]:
#vemos si podemos salvar algunos titulos, cuyas filas son NaN
df_games_copy[df_games_copy.title.isnull()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
2579,NaN,"[Action, Indie]",NaN,NaN,http://store.steampowered.com/app/317160/_/,2014-08-26,"[Action, Indie]",http://steamcommunity.com/app/317160/reviews/?...,NaN,"[Single-player, Game demo]",NaN,False,317160,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_games_copy = df_games_copy.drop(df_games_copy.index[2579])
df_games_copy.reset_index(drop=True, inplace=True)

In [ ]:
df_games_copy.isnull().sum()

publisher          8050
genres             3282
app_name              0
title                 0
url                   0
release_date       2066
tags                162
reviews_url           1
discount_price    31909
specs               669
price              1376
early_access          0
id                    0
metascore         29456
developer          3297
user_id           32133
steam_id          32133
items             32133
items_count       32133
dtype: int64

In [ ]:
#vemos que poseen datos similares Entonces completamos los fatantes en uno con el otro
df_games_copy['genres'].fillna(df_games_copy['tags'], inplace=True)
df_games_copy['tags'].fillna(df_games_copy['genres'], inplace=True)

In [ ]:
df_games_copy = df_games_copy.drop('tags', axis = 1)

In [ ]:
df_games_copy.isnull().sum()

publisher          8050
genres              138
app_name              0
title                 0
url                   0
release_date       2066
reviews_url           1
discount_price    31909
specs               669
price              1376
early_access          0
id                    0
metascore         29456
developer          3297
user_id           32133
steam_id          32133
items             32133
items_count       32133
dtype: int64

In [ ]:
#funcion para convertir palabras en precio = 0
def convertir_precio(valor):
    try:
        return float(valor)
    except (ValueError, TypeError):
        return 0

In [ ]:
df_games_copy['price'] = df_games_copy['price'].apply(convertir_precio).fillna(0)

In [ ]:
df_games_copy.isnull().sum()

publisher          8050
genres              138
app_name              0
title                 0
url                   0
release_date       2066
reviews_url           1
discount_price    31909
specs               669
price                 0
early_access          0
id                    0
metascore         29456
developer          3297
user_id           32133
steam_id          32133
items             32133
items_count       32133
dtype: int64

In [ ]:
df_games_copy = df_games_copy.dropna(subset=['genres','release_date'])

In [ ]:
df_games_copy.isnull().sum()

publisher          5941
genres                0
app_name              0
title                 0
url                   0
release_date          0
reviews_url           1
discount_price    29726
specs               662
price                 0
early_access          0
id                    0
metascore         27308
developer          1223
user_id           29930
steam_id          29930
items             29930
items_count       29930
dtype: int64

In [ ]:
df_games_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29930 entries, 0 to 32131
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       23989 non-null  object
 1   genres          29930 non-null  object
 2   app_name        29930 non-null  object
 3   title           29930 non-null  object
 4   url             29930 non-null  object
 5   release_date    29930 non-null  object
 6   reviews_url     29929 non-null  object
 7   discount_price  204 non-null    float64
 8   specs           29268 non-null  object
 9   price           29930 non-null  float64
 10  early_access    29930 non-null  object
 11  id              29930 non-null  object
 12  metascore       2622 non-null   object
 13  developer       28707 non-null  object
 14  user_id         0 non-null      object
 15  steam_id        0 non-null      object
 16  items           0 non-null      object
 17  items_count     0 non-null      float64
dtypes: float64(3), object(15)
memory usage: 4.3+ MB

In [ ]:
df_games_copy

,publisher,genres,app_name,title,url,release_date,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,http://steamcommunity.com/app/761140/reviews/?...,4.49,[Single-player],4.99,False,761140,NaN,Kotoshiro,NaN,NaN,NaN,NaN
1,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,http://steamcommunity.com/app/643980/reviews/?...,NaN,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,NaN,Secret Level SRL,NaN,NaN,NaN,NaN
2,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,http://steamcommunity.com/app/670290/reviews/?...,NaN,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,NaN,Poolians.com,NaN,NaN,NaN,NaN
3,彼岸领域,"[Action, Adventure, Casual]",弹炸人2222,弹炸人2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,http://steamcommunity.com/app/767400/reviews/?...,0.83,[Single-player],0.99,False,767400,NaN,彼岸领域,NaN,NaN,NaN,NaN
5,Trickjump Games Ltd,"[Action, Adventure, Simulation]",Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,2018-01-04,http://steamcommunity.com/app/772540/reviews/?...,NaN,"[Single-player, Steam Achievements]",3.99,False,772540,NaN,Trickjump Games Ltd,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32127,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,Kebab it Up!,http://store.steampowered.com/app/745400/Kebab...,2018-01-04,http://steamcommunity.com/app/745400/reviews/?...,1.69,"[Single-player, Steam Achievements, Steam Cloud]",1.99,False,745400,NaN,Bidoniera Games,NaN,NaN,NaN,NaN
32128,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,http://steamcommunity.com/app/773640/reviews/?...,1.49,"[Single-player, Steam Achievements]",1.99,False,773640,NaN,"Nikita ""Ghost_RUS""",NaN,NaN,NaN,NaN
32129,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,http://steamcommunity.com/app/733530/reviews/?...,4.24,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,NaN,Sacada,NaN,NaN,NaN,NaN
32130,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,http://steamcommunity.com/app/610660/reviews/?...,1.39,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,NaN,Laush Dmitriy Sergeevich,NaN,NaN,NaN,NaN
32131,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,http://steamcommunity.com/app/658870/reviews/?...,NaN,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,NaN,"xropi,stev3ns",NaN,NaN,NaN,NaN

In [ ]:
#eliminamos columnas con mucha informacion faltante: metascore, discount_price;  
#app_name por ser similar a title, y las url por no aportar valor
df_games_copy.drop(['app_name','metascore','discount_price','reviews_url','url', 'publisher', 'developer' ], inplace=True, axis=1)
df_games_copy.drop(['specs','user_id','steam_id','items','items_count',  'early_access', 'price' ], inplace=True, axis=1)

In [ ]:
#cambiamos el tipo de datos de id para poder gurdar como parquet sin que de error y renombramos
df_games_copy['id'] = df_games_copy['id'].apply(lambda x: x.to_bytes(4, byteorder='big') if isinstance(x, int) else x)
df_games_copy.rename(columns={'id': 'item_id'}, inplace=True)
df_games_copy.reset_index(drop=True, inplace=True)

In [ ]:
df_games_copy

,genres,title,release_date,price,item_id
0,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,2018-01-04,4.99,761140
1,"[Free to Play, Indie, RPG, Strategy]",Ironbound,2018-01-04,0.00,643980
2,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,2017-07-24,0.00,670290
3,"[Action, Adventure, Casual]",弹炸人2222,2017-12-07,0.99,767400
4,"[Action, Adventure, Simulation]",Battle Royale Trainer,2018-01-04,3.99,772540
...,...,...,...,...,...
29925,"[Action, Adventure, Casual, Indie]",Kebab it Up!,2018-01-04,1.99,745400
29926,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,2018-01-04,1.99,773640
29927,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,2018-01-04,4.99,733530
29928,"[Indie, Racing, Simulation]",Russian Roads,2018-01-04,1.99,610660
29929,"[Casual, Indie]",EXIT 2 - Directions,2017-09-02,4.99,658870

In [ ]:
df_games_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29930 entries, 0 to 29929
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        29930 non-null  object
 1   title         29930 non-null  object
 2   release_date  29930 non-null  object
 3   price         29930 non-null  float64
 4   item_id       29930 non-null  object
dtypes: float64(1), object(4)
memory usage: 1.1+ MB

In [ ]:
# Especifica el nombre del archivo Parquet en el que deseas guardar el DataFrame
nombre_archivo_parquet = "data_games.parquet"

# Guarda el DataFrame como un archivo Parquet
df_games_copy.to_parquet(nombre_archivo_parquet)

In [3]:
df_games = pd.read_parquet('data_games.parquet')

In [5]:
df_games['item_id'] = df_games['item_id'].str.decode('utf-8')
# Convertir la columna 'release_date' a tipo datetime, manejando errores
df_games['release_date'] = pd.to_datetime(df_games['release_date'], errors='coerce')
# Filtrar filas con fechas válidas (no NaN)
df_games = df_games.dropna(subset=['release_date'])
#expandir la columna genres
df_games = df_games.explode('genres',ignore_index=True)
#filtramos y llevamos a minusculas
df_games['genres'] = df_games['genres'].fillna('')
df_games['genres'] = df_games['genres'].str.lower()

In [10]:
df_games.drop('price',axis =1, inplace=True)

In [6]:
nombre_archivo_parquet = "data_games_explode.parquet"
# Guarda el DataFrame como un archivo Parquet
df_games.to_parquet(nombre_archivo_parquet)